inputs:
  folders:
    description: Space-separated folder paths to check for changes
    required: false
    default: "data frontend shared"

outputs:
  should_deploy:
    description: "true if changes occurred in monitored folders"
    
runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        git fetch origin ${{ github.event.before }} --depth=1
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "$CHANGED"

        PATTERN=$(echo "${{ inputs.folders }}" | sed 's/ /\\|/g')
        if echo "$CHANGED" | grep -qE "^($PATTERN)/"; then
          echo "should_deploy=true" >> $GITHUB_OUTPUT
        else
          echo "should_deploy=false" >> $GITHUB_OUTPUT
        fi
