name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [crawler, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Build ${{ matrix.target }}
        run: pnpm run ${{ matrix.target }}:build

  lint:
    name: Lint ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        target: [crawler, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Lint ${{ matrix.target }}
        run: pnpm run ${{ matrix.target }}:lint
