name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [crawler, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Build ${{ matrix.target }}
        run: pnpm run ${{ matrix.target }}:build

  lint:
    name: Lint ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        target: [crawler, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Lint ${{ matrix.target }}
        run: pnpm run ${{ matrix.target }}:lint

  check:
    name: Check If Deployment Is Needed
    runs-on: ubuntu-latest
    needs: [build, lint]
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if deploy is needed
        id: check
        shell: bash
        run: |
          git fetch origin ${{ github.event.before }} --depth=1
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$CHANGED"

          PATTERN="data|frontend|shared"
          if echo "$CHANGED" | grep -qE "^($PATTERN)/"; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Vercel Deployment
    runs-on: ubuntu-latest
    needs: [build, lint, check]
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') && needs.check.outputs.should_deploy == 'true'

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm

      - name: Pull Vercel Environment Info
        run: |
          ENVIRONMENT=$( [ "${{ github.event_name }}" = "pull_request" ] && echo "preview" || echo "production" )
          pnpm dlx vercel pull --yes --environment=$ENVIRONMENT --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          FLAG=$( [ "${{ github.ref }}" = "refs/heads/main" ] && echo "--prod" || echo "" )
          pnpm dlx vercel build $FLAG --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          FLAG=$( [ "${{ github.ref }}" = "refs/heads/main" ] && echo "--prod" || echo "" )
          pnpm dlx vercel deploy --prebuilt $FLAG --token=${{ secrets.VERCEL_TOKEN }}
