name: Weekly Preview Publish

on:
  schedule:
    - cron: "0 22 * * 0" # Every Sunday at 22:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm

      - name: Run crawler with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm run crawler:start
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Set dynamic branch name
        id: branch
        run: echo "name=issue/$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_GITHUB }}
          commit-message: "chore: publish weekly issue"
          branch: ${{ steps.branch.outputs.name }}
          committer: GitHub Actions Bot <actions@github.com>
          author: GitHub Actions Bot <actions@github.com>
          title: "chore: publish weekly issue"
          body: "Automated weekly issue content update"
          labels: |
            automated pr
