name: Weekly Release

on:
  schedule:
    - cron: "0 3 * * 2" # Every Tuesday at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find preview PR
        id: pr
        run: |
          PR_JSON=$(gh pr list \
            --state open \
            --base main \
            --search "head:weekly/preview" \
            --json number,title,headRefName \
            --jq '.[0]')

          if [ -z "$PR_JSON" ] || [ "$PR_JSON" == "null" ]; then
            echo "No matching PR found."
            echo "found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          echo "Found PR #$NUMBER"
          echo "found=true" >> $GITHUB_OUTPUT
          echo "number=$NUMBER" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.pr.outputs.found == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}
          pull-request-number: ${{ steps.pr.outputs.number }}
          merge-method: squash

      - name: Merge the PR
        if: steps.pr.outputs.found == 'true'
        run: gh pr merge ${{ steps.pr.outputs.number }} --squash --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
