name: Weekly Release

on:
  schedule:
    - cron: "0 3 * * 2" # Every Tuesday at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find preview PR
        id: pr
        run: |
          PR_JSON=$(gh pr list \
          --state open \
          --base main \
          --json number,title,headRefName,author \
          | jq -c '[.[] | select(.headRefName | startswith("weekly/preview")) | select(.author.email == "actions@github.com")][0]')
          
          if [ -z "$PR_JSON" ]; then
            echo "No matching PR found."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          HEAD=$(echo "$PR_JSON" | jq -r '.headRefName')

          echo "Found PR #$NUMBER ($HEAD)"
          echo "number=$NUMBER" >> $GITHUB_OUTPUT
          echo "skip=false" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.pr.outputs.skip == 'false'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.number }}
          merge-method: squash

      - name: Merge the PR
        if: steps.pr.outputs.skip == 'false'
        run: gh pr merge ${{ steps.pr.outputs.number }} --squash --admin --delete-branch --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
