name: Weekly Preview Publish

on:
  schedule:
    - cron: "0 20 * * 0" # Every Sunday at 20:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm

      - name: Run crawler
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pnpm run crawler:start

      - name: Set dynamic branch name
        id: branch
        run: echo "name=weekly/preview-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_GITHUB }}
          commit-message: "chore: weekly preview publish"
          branch: ${{ steps.branch.outputs.name }}
          title: "chore: weekly preview publish"
          body: "Automated weekly preview content update."
          labels: |
            automated pr
