name: Weekly Social Notifications

on:
  schedule:
    - cron: "0 8 * * 2" # Every Tuesday at 08:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: pnpm run social:start
