name: Weekly Preview Publish

on:
  schedule:
    - cron: "0 20 * * 0" # Every Sunday at 20:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm

      - name: Run crawler
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pnpm run crawler:start

      - name: Create pull request
        id: create-pr
        run: |
          BRANCH_NAME="weekly/preview-$(date +'%Y-%m-%d')"

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git checkout -b "$BRANCH_NAME"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          git commit -m "chore: weekly preview publish"
          git push origin "$BRANCH_NAME"

          echo "skip=false" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Open pull request
        if: steps.create-pr.outputs.skip == 'false'
        run: |
          gh pr create \
            --title "chore: weekly preview publish" \
            --body "Automated weekly preview content update." \
            --head "${{ steps.create-pr.outputs.branch }}" \
            --base "main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
